// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzzaioompmomwkspfnrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6emFpb29tcG1vbXdrc3BmbnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMDcxOTMsImV4cCI6MjA1MDg4MzE5M30.OWckyj0Bc1M9_fDsZT_N90H2xyKvHUcZ0Rv_hfJE04M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);